{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-services-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
        {{- range $name, $svc := .Values.services }}
        {{- if $svc.enabled }}
        - {{ $svc.ingress.host }}
        {{- end }}
        {{- end }}
      secretName: email-services-tls
  rules:
    {{- range $name, $svc := .Values.services }}
    {{- if $svc.enabled }}
    - host: {{ $svc.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $svc.service.port }}
    {{- end }}
    {{- end }}
{{- end }}
