{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ $name }}
---
{{- end }}
{{- end }}
