[common]
server_addr = "8.152.195.33"
server_port = 7001
token = "yyc3_nas"
user = "nas_client"
admin_addr = "127.0.0.1"
admin_port = 7400
admin_user = "yyc3"
admin_pwd = "my151001"
log_file = "/Volume2/www/frpc/logs/frpc.log"
log_level = "info"
log_max_days = 7
tcp_mux = true
heartbeat_timeout = 60
heartbeat_interval = 30
tls_enable = true

[api-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 3000
remote_port = 5001
custom_domains = "api.0379.email"

[llm-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 8000
remote_port = 5002
custom_domains = "llm.0379.email"

[admin-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 3001
remote_port = 5003
custom_domains = "admin.0379.email"

[mail-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 3003
remote_port = 5004
custom_domains = "mail.0379.email"

[nas-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 80
remote_port = 5005
custom_domains = "nas.0379.email"

[monitor-0379]
type = "tcp"
local_ip = "192.168.3.45"
local_port = 3002
remote_port = 5006
custom_domains = "monitor.0379.email"